In [4]:
print("hello")


hello


In [6]:
# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in

height_in = [8,9,19,16,15,14,12,18]

np_height_in = np.array(height_in)

# Print out np_height_in

print(np_height_in)

# Convert np_height_in to m: np_height_m

np_height_m = np_height_in*0.0254

# Print np_height_m

print(np_height_m)
print(np_height_m[4])

[ 8  9 19 16 15 14 12 18]
[0.2032 0.2286 0.4826 0.4064 0.381  0.3556 0.3048 0.4572]
0.381


In [12]:
import numpy as np

DD = [[8,9,19,16,15,14,12,18],[1,2,3,4,5,6,7,8]]

DD_A = np.array(DD)
DD_AA = DD_A[:,1]

print(DD_A[:,1])
print(DD_A[1,:])


[9 2]
[1 2 3 4 5 6 7 8]
